### ISSUE TITLE
composer a namespace

### ISSUE THREAD

**Issue by techi602** [seznam/zbozi-konverze#1]
Řada vývojářů by jistě ocenila i instalaci přes composer a zabalení do jmenného prostoru, což je v PHP  už pár let a bylo by hezké, kdyby i programátoři seznamu také začali pomalu inovovat :)

**Comment by TomasVotruba** [comment]
PR?

**Comment by soukicz** [comment]
Problém bude, že už je to vedené jako stable a tahle změna to všem rozbije.

Udělal jsem proto vlastní balíček, který už namespace má rovnou - https://github.com/soukicz/zbozicz

**Comment by che0** [comment]
Díky velmi za poznámku. Rozmýšlíme co provést se zpětnou kompatibilitou, ale alternativním implementacím se rozhodně nebráníme, ať už v PHP nebo jiných jazycích.

**Comment by che0** [comment]
V zájmu zpětné kompatibility se staršími PHPky necháme tenhle modul tak jak je. Do popisu jsem přidal odkaz na druhou implementaci od @soukicz (děkujeme!), kdo o ní bude mít zájem snad najde.
