### ISSUE TITLE
Více čísel objednávek z frontend

### ISSUE THREAD

**Issue by SeppJorgen** [seznam/zbozi-konverze#10]
Z dokumentace plyne, že nelze nastavit více než jedno ID objednávky. Bohužel volání "privátních" metod pluginu či složité unloudování scriptu není šťastné ani udržitelné řešení. Existuje nějaká cesta pro to, abych buď najednou nebo iterací odeslal z frontend části více než jedno ID? Například rozeznání jestli hodnota v proměnné `seznam_orderId ` je pole či string.

**Comment by che0** [comment]
Přiznávám že jsem ještě neviděl e-shopový systém, který by mi umožnil z jednoho košíku vytvořit několik různých objednávek. Můžete prosím rozvést k čemu by taková funkčnost byla dobrá?

**Comment by SeppJorgen** [comment]
Na e-shopu, který vyvíjíme jsou některé produkty z externího skladu dodavatele. V košíku se následně objednávka rozdělí na dva balíky (dvě objednávky), protože produkty z externího skladu se posílají pouze dopravou DPD a na přímo k zákazníkovy. Zákazník je o daném procesu samozřejmě patřičně informován v košíku.
Důvodů proč je to takhle implementováno je několik - technická implementace systému třetí strany, administrativní zatížení/důvody, ale hlavně kvůli faktu, že jde o samostatné balíky doručené jinou dopravní společností.

Každopádně dokáži si představit, že by se podobná "praktika" dělala cíleně. Například v případě neskladovosti jednoho z produktů, že by jste si mohl nechat doručit produkty, které jsou skladem a zbytek odděleně až bude produkt naskladněn. V tomhle případě jak pro zákazníka tak pro e-shop je lepší to rozdělit fyzicky na 2 objednávky. Další funkčnosti při kterých by se rozdělení dělo bych určitě ještě vymyslel.

Z mé osobní zkušenosti znám více e-shopů, které posílá více balíků jinými dopravními společnostmi. Jenom někteří na informovanost pro zákazníka hledí a jiní ne.

**Comment by che0** [comment]
Jasně, chápu. To bych si ale dovolil popsat jako jednu objednávku, která jde dvěma balíky (nebo můžeme říkat "dodávkami") -- zákazník naplní jeden košík a pokud platí předem tak to platí celé najednou (alespoň bych to tedy coby zákazník čekal).

A co je podle mě podstatnější z hlediska propojení: pokud je ten košík výsledkem (konverzí) nějakého prokliku, dává mi smysl ho započítat celý. Pokud byste to (minimálně ve Zboží, ale počítám že to bude i v dalších PPC) počítal jako dvě objednávky, započítá se vám konverze jen u té první, což vám rozhodí metriky. A pokud používáte standardní měření, vygenerovaly by se i dva e-maily na hodnocení obchodu, což by zákazníka nejspíš nepotěšilo.

Tuto situaci bych tedy doporučoval řešit tím že do konverzního kódu pošlete jednu společnou objednávku s celým košíkem, byť šel třeba více dodávkami.
