### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by 1kdesign** [seznam/zbozi-konverze#11]
Dobry den,
z niceho nic nam konverzi skript zacal psat nasledujici hlasku

Uncaught exception 'ZboziKonverzeException' with message 'Unable to establish connection to ZboziKonverze service: SSL certificate problem: certificate has expired

U nas se s certifikatem nic nedelalo, mohl by mi prosim nekdo poradit co s tim? Dekuji

**Comment by che0** [comment]
Dobrý den, problém je v chainu certifikačních autorit. www.zbozi.cz používá Let's Encrypt certifikát odvozený z autority "ISRG Root X1", podepsanou další autoritou "DST Root CA X3", které ovšem 30. září skončila platnost.

ISRG Root X1 by měly uznávat všechny alespoň trochu nové systémy, problémy můžou mít Windows XP před SP3, Debian Wheezy, Java před verzí 8u141, [a nějaké další](https://letsencrypt.org/docs/certificate-compatibility/). Řešením je přidat ISRG Root X1, na některých verzích Debianu stačí odebrat již neplatnou DST Root CA X3 (protože jí SSL knihovna při hledání autority najde jako první a pak se na ní rozbije).

Celkově asi záleží na platformě kde vám skript běží. Možná pomůže i blog post zde: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by karolwisniewski88** [comment]
Dobrý den, vím, že se jedná o staré téma, ale dnes se setkávám se stejným problémem. Testoval(a) jsem na Zbozi sandboxu na dvou různých operačních systémech: Kubuntu 22.04 a MacOS 13.4 (nejnovější verze) v aktualizovaných prohlížečích Chrome a Firefox. Mám nainstalované nejnovější balíčky ca-certificates. Co ještě lze udělat, aby se tento problém nevyskytoval? S pozdravem.

**Comment by che0** [comment]
Dobrý den, jestli vám dotyčnou chybu hlásí váš konverzní skript běžící na serveru tak vůbec nezáleží v jakém prohlížeči na stránku koukáte. Spíš se podívejte na nastavení certifikátů na serveru. Jde vám přes PHP curl/file_get_contents načíst například https://www.php.net/?

**Comment by PanTau674** [comment]
Nám se problém vyřešil tím, že jsme zkontaktovali hostingovou firmu, kde máme e-shop a oni obnovili KOŘENOVÝ CERTIFIKÁT.
