### ISSUE TITLE
Compression error

### ISSUE THREAD

**Issue by haianhxanh** [seznam/zbozi-konverze#16]
Dobrý den, při odesílání dat ze Shopify pomocí metody GET jsme narazili na error:

```
Encountered a compression error: the server returned a compressed response body, but the body was not valid deflate data.

This is usually caused by a misconfigured web server. Please contact the webmaster of the site you're trying to connect to, and ask them to fix their server configuration.

Response code:
200
```

Přitom stejná implementace úspěšně prošla testovacím prostředím. Budu ráda za jakékoliv rady. Děkuji.

**Comment by che0** [comment]
Dobrý den, upřímně ani nemám pocit že by někde na serverech bylo deflate povolené. Na jakou URL ten GET posíláte, a čím?

**Comment by haianhxanh** [comment]
Dobrý den, děkuji za reakci. 

Data odesíláme ze Shopify pomocí aplikace [Mechanic](https://mechanic.dev/). Do konce minulého roku vše fungovalo bez problému. 

Zde je URL, na kterou GET posíláme

`https://www.zbozi.cz/action/<STORE_ID>/conversion/backend?orderId=<ORDER_ID>&PRIVATE_KEY=<KEY>&deliveryType=VLASTNI_PREPRAVA&email=<EMAIL>&cart=itemId:<ITEM_ID>;quantity:<QUANTITY>;unitPrice:<PRICE>;productName:<PRODUCT_NAME>` 

Pro sandbox prostředí jsme použili tuto URL
`https://sandbox.zbozi.cz/action/<SANDBOX_STORE_ID>/conversion/backend?orderId=<ORDER_ID>&PRIVATE_KEY=<SANDBOX_KEY>&deliveryType=VLASTNI_PREPRAVA&email=<EMAIL>&cart=itemId:<ITEM_ID>;quantity:<QUANTITY>;unitPrice:<PRICE>;productName:<PRODUCT_NAME>` 

Vše proběhlo v pořádku, přišla nám tato odpověď:
`"body": {
    "status": 200,
    "statusMessage": "OK",
    "apiVersion": 2
  }
 `
 
 Proto nechápu, proč na produkci nám to nefunguje. Zde je úplná chybová hláška
 
 `
Action error
Encountered a compression error: the server returned a compressed response body, but the body was not valid deflate data.

This is usually caused by a misconfigured web server. Please contact the webmaster of the site you're trying to connect to, and ask them to fix their server configuration.

Response code:
200

Response headers:
{
  "server": [
    "envoy"
  ],
  "date": [
    "Mon, 27 Mar 2023 23:01:48 GMT"
  ],
  "content-type": [
    "application/json"
  ],
  "content-length": [
    "45"
  ],
  "vary": [
    "Accept-Encoding"
  ],
  "content-encoding": [
    "deflate"
  ],
  "strict-transport-security": [
    "max-age=15724800; includeSubDomains"
  ],
  "referrer-policy": [
    "origin"
  ],
  "access-control-allow-origin": [
    "*"
  ],
  "x-envoy-upstream-service-time": [
    "87"
  ]
}

Response body (base64-encoded):
q1YqLkksKS1WsjIyMNCBcnxTi4sT01OVrJT8vZV0lBILMsNSi4oz8/OAqmoB`
 
 
 Předem děkuji za nahlédnutí do problému.

**Comment by che0** [comment]
Koukal jsem na to, a přijde mi že deflate neposíláme vůbec, a nemocné je něco mezi Shopify a AWS. Zkusil jsem několikrát reprodukovat váš request (což zároveň znamená že se e-shopu může ukázat ve výpisu chyb, omlouvám se za případné komplikace), a v curlu to vypadá následovně:

```
curl -A 'Mechanic/██████████.myshopify.com (+https://usemechanic.com/)' -v 'https://www.zbozi.cz/action/█████/conversion/backend?orderId=5528506106179XZ&PRIVATE_KEY=████████████████████████████████&deliveryType=VLASTNI_PREPRAVA&email=████%40seznam.cz&cart=itemId:40230672761022;quantity:1;unitPrice:3429.00;productName:BEZDR%C3%81TOV%C3%9D+TEPLOM%C4%9AR+MEATER%2BKONVERZE-POKUS'
*   Trying 77.75.78.3:443...
* TCP_NODELAY set
* Connected to www.zbozi.cz (77.75.78.3) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=zbozi.cz
*  start date: Mar 19 06:02:43 2023 GMT
*  expire date: Jun 17 06:02:42 2023 GMT
*  subjectAltName: host "www.zbozi.cz" matched cert's "*.zbozi.cz"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /action/█████/conversion/backend?orderId=5528506106179XZ&PRIVATE_KEY=████████████████████████████████&deliveryType=VLASTNI_PREPRAVA&email=████%40seznam.cz&cart=itemId:40230672761022;quantity:1;unitPrice:3429.00;productName:BEZDR%C3%81TOV%C3%9D+TEPLOM%C4%9AR+MEATER%2BKONVERZE-POKUS HTTP/1.1
> Host: www.zbozi.cz
> User-Agent: Mechanic/██████████.myshopify.com (+https://usemechanic.com/)
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< server: envoy
< date: Wed, 29 Mar 2023 10:24:19 GMT
< content-type: application/json
< content-length: 50
< vary: Accept-Encoding
< strict-transport-security: max-age=15724800; includeSubDomains
< referrer-policy: origin
< access-control-allow-origin: *
< x-envoy-upstream-service-time: 117
< 
* Connection #0 to host www.zbozi.cz left intact
{"status":200,"statusMessage":"OK","apiVersion":2}
```

Nic v deflate tam není. Není možné že to dělá nějaká AWS proxy nebo další zpracování v Mechanicu?

**Comment by che0** [comment]
Můžete se zkusit jejich podporu, poslat jim výpis z curl a optat se proč to u nich ukazuje compression hlavičku s rozbitým obsahem.

Jak přesně funguje Make nevím, ale pokud by automatizace v intervalu 15 minut znamenala že backendové částí konverzí budou chodit se zpožděním, tak to by nemělo vadit -- Zboží dovede spojit informace s časovým odstupem až 30 minut.
