### ISSUE TITLE
pro backend konverze chybí consent parametr

### ISSUE THREAD

**Issue by marekcech** [seznam/zbozi-konverze#18]
Krásný den, bojuji s problémem, že se nám pořád vypíná měření konverzí z důvodu, že Vám chybí data z backend části. Důvod je ten, že v backendovém konverzním kódu nemáte parametr pro consent a tak vám data u zákazníků, kteří nedali souhlas se zpracováním jejich údajů ty konverze prostě neposíláme, protože nedokážeme zaručit, že jejich údaje nezpracujete i bez jejich souhlasu.

Můžete se na to podívat a případně vysvětlit, jak si představujete, že má být tato situace řešena? 
Tj. uživatel na webu nedá souhlas s měřením, nedá souhlas se zasíláním žádných údajů apod. Na Frontendu konverzní kód spustíme a dáme mu parametr consent = 0, ale na backednu ho logicky nespustíme. Tím pádem to začne v administraci kričet, že to nefunguje a za chvíli se konverze vypnou.
Pokud vám i na frontentu budeme posílat pouze consentované konverze, tak se zase klientovi ozve nějaký Sklik / Zboží optimalizátor, že je zvláštní, že posíláme data pouze se souhlasem.....

Díky budu rád, když najdeme ideální řešení.

**Comment by che0** [comment]
Obecně byste měli ve všech případech volat jak frontend, tak i backend část. Oba kusy spojujeme (ostatně proto vám to hází chyby), a z výsledné informace využíváme:

- pole `consent` z frontendu pro informaci, zda zákazník sohlasil s využitím cookies mj. pro měření konverzí
- pole `email` z backendu pro ověření spokojenosti s nákupem a žádost o ohodnocení zakoupeného produktu

Tedy:

- Pokud od zákazníka nemáte souhlas s využíváním cookies pro retargeting a měření (typicky přes všudypřítomné cookie lišty), měl byste do Zboží poslat jak frontend, tak i backend, s tím že na frontendu uvedete `consent: 0`
- Pokud od zákazníka nemáte souhlas se zasláním dotazníku pro hodnocení nákupu (typicky tím, že v košíku zaškrtne checkbox "nesouhlasím ze zasláním dotazníku spokojenosti"), měl byste do Zboží poslat jak frontend, tak i backend, s tím že v backendu neuvedete pole `email`.

Obě políčka jsou na sobě nezávislá, takže se může stát, že zákazník souhlasí s cookies, ale ne s (předáním e-mailu pro) hodnocení, případně naopak. Pokud nesouhlasí ani s jedním, pak byste nám měl opět poslat frontend i backend, s tím že na front-endu uvedene `consent: 0`, a na backendu neuvedete pole `email`.

Zboží ve všech případech zpracujete data podle toho, k čemu má souhlas. Pokud nedostaneme souhlas s využitím dat (t.č. převážně cookies) pro měření konverzí a cílení, pak na daného zákazníka nebudeme cílit, a to ani když v backendu pošlete jeho e-mailovou adresu v poli `email` -- ta je využívána výhradně pro odeslání dotazníků k vyhodnocení spokojenosti s nákupem a zakoupeným produktem.

**Comment by SukiCZ** [comment]
Bylo by skvělý mít toto zdokumentováno (že se mají posílat údaje **vždy**/**ve všech případech**).

Děkuji
