### ISSUE TITLE
Prochází jen některé transakce

### ISSUE THREAD

**Issue by PremyslNeuman** [seznam/zbozi-konverze#5]
Provedli jsme impementaci pokročilého měření. Na testu nám funguje vše OK. Na ostrém však transakce neprochází. Resp. prošly asi dvě z padesáti. V logu odeslání JSON requestu je OK. Vrací status OK (200). Exsituje diagnostika, případně nějaký support, jak zjistit, kde je problém ? Děkuji.

**Comment by che0** [comment]
Co přesně znamená "transakce neprochází"? Jestli se vám v sekci "Konverze přijaté z Vašeho obchodu za poslední 3 dny" ukázaly asi dvě transakce z padesáti tak to znamená že dvě z padesáti vzniklých objednávek jsou konverze ze Zboží, což zní celkem reálně.

Na diagnostiku slouží právě sandbox, jestli v něm vše funguje jak má tak je vysoká šance že to půjde i na ostrém. Support pro e-shopy poskytujeme přes [kontakty v nápovědě](https://napoveda.seznam.cz/cz/zbozi/kontaktni-formular-zbozi/).

**Comment by PremyslNeuman** [comment]
Dobrý den, děkuji. Myslel jsem, že v administraci se zobrazují všechny transakce. Ale toto by to vysvětlovalo. Děkuji.

**Comment by che0** [comment]
Nemáte zač, kdysi tam všechny byly, ale odstranili jsme je aby zákazníky nemátly :-)
