### ISSUE TITLE
Proč backend?

### ISSUE THREAD

**Issue by mzvarik** [seznam/zbozi-konverze#8]
Proč jste to udělali takto?
Jste nemohli udělat jenom PHP nebo jenom Javascript jako všichni?
Javascriptem asi chcete sledovat náštěvníka, ale proč dávat zvlášť ještě PHP tomu nerozumím.
No aspoň je k tomu API a příklad, děkuji.

**Comment by che0** [comment]
Dobrý den, tohle řešení vyplývá ze snahy spolehlivě měřit konverze.

* front-end (Javascript) volání je tam proto, že potřebujeme cookie z prohlížeče zákazníka, abychom dokázali zjistit jestli jde o konverzi (tj. zda před nákupem proklikl ze Zboží do e-shopu). Počty konverzí jsou klíčové pro vyhodnocování inzerce.
* back-end (PHP) volání je tam proto, že chceme e-shopům ukazovat důvěryhodná čísla, a pokud máte pouze front-end kód tak jsou všechny obsažené informace v zásadě veřejné a kdokoli s trochou motivace je může zkopírovat a nakrmit vám statistiky hromadami blbostí
